title: Max Paterson

logo: /images/Profilepic.jpg

description: |
  Data Analyst | Business Intelligence | Python | SQL | Power BI

  Please Contact for Resume

  Phone Number: (403) 471-3115

  Email: Max.r.paterson@gmail.com

  <a href="https://www.linkedin.com/in/maxwellpaterson/" target="_blank">
    Dont View My LinkedIn Profile
  </a>

theme: null

markdown: kramdown

github:
  is_project_page: false